title: Lagomorph AI Documentation
description: Documentation for Lagomorph AI - 3D asset generation for game developers
theme: just-the-docs
logo: "/images/logo-cropped.png"
favicon_ico: "/images/favicon.ico"

url: https://lagomorphai.github.io/lagomorph_docs

aux_links:
  Back to Homepage: https://lagomorph.ai/
  Start Creating: https://app.lagomorph.ai
  Discord: https://discord.gg/RsNwwy3WCc
aux_links_new_tab: true

color_scheme: lagomorph
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
